export interface Cnae {
  codigo: string;
  titulo: string;
}

// CNAEs más comunes (CNAE-2009). Formato: "XXXX - Título"
export const CNAES: Cnae[] = [
  { codigo: "0111", titulo: "Cultivo de cereales (excepto arroz), leguminosas y semillas oleaginosas" },
  { codigo: "0112", titulo: "Cultivo de arroz" },
  { codigo: "0113", titulo: "Cultivo de hortalizas, raíces y tubérculos" },
  { codigo: "0119", titulo: "Otros cultivos no perennes" },
  { codigo: "0121", titulo: "Cultivo de la vid" },
  { codigo: "0122", titulo: "Cultivo de frutos tropicales y subtropicales" },
  { codigo: "0123", titulo: "Cultivo de cítricos" },
  { codigo: "0124", titulo: "Cultivo de frutas con hueso y pepitas" },
  { codigo: "0125", titulo: "Cultivo de otros árboles y arbustos frutales y frutos secos" },
  { codigo: "0126", titulo: "Cultivo de frutos oleaginosos" },
  { codigo: "0127", titulo: "Cultivo de plantas para bebidas" },
  { codigo: "0128", titulo: "Cultivo de especias, plantas aromáticas, medicinales y farmacéuticas" },
  { codigo: "0129", titulo: "Otros cultivos perennes" },
  { codigo: "0130", titulo: "Propagación de plantas" },
  { codigo: "0141", titulo: "Explotación de ganado bovino para la producción de leche" },
  { codigo: "0142", titulo: "Explotación de otro ganado bovino y búfalos" },
  { codigo: "0143", titulo: "Explotación de caballos y otros equinos" },
  { codigo: "0145", titulo: "Explotación de ganado ovino y caprino" },
  { codigo: "0146", titulo: "Explotación de ganado porcino" },
  { codigo: "0147", titulo: "Avicultura" },
  { codigo: "0149", titulo: "Otras explotaciones de ganado" },
  { codigo: "0150", titulo: "Producción agrícola combinada con la producción ganadera" },
  { codigo: "0161", titulo: "Actividades de apoyo a la agricultura" },
  { codigo: "0162", titulo: "Actividades de apoyo a la ganadería" },
  { codigo: "0163", titulo: "Actividades de poscosecha" },
  { codigo: "0164", titulo: "Preparación de las semillas" },
  { codigo: "0170", titulo: "Caza, captura de animales y servicios relacionados" },
  { codigo: "0210", titulo: "Silvicultura y otras actividades forestales" },
  { codigo: "0220", titulo: "Explotación de la madera" },
  { codigo: "0230", titulo: "Recolección de productos silvestres, excepto madera" },
  { codigo: "0240", titulo: "Servicios de apoyo a la silvicultura" },
  { codigo: "0311", titulo: "Pesca marina" },
  { codigo: "0312", titulo: "Pesca en agua dulce" },
  { codigo: "0321", titulo: "Acuicultura marina" },
  { codigo: "0322", titulo: "Acuicultura en agua dulce" },
  { codigo: "0510", titulo: "Extracción de antracita, hulla y lignito" },
  { codigo: "0520", titulo: "Extracción de lignito" },
  { codigo: "0610", titulo: "Extracción de crudo de petróleo" },
  { codigo: "0620", titulo: "Extracción de gas natural" },
  { codigo: "0710", titulo: "Extracción de minerales de hierro" },
  { codigo: "0721", titulo: "Extracción de minerales de uranio y torio" },
  { codigo: "0729", titulo: "Extracción de otros minerales metálicos no férreos" },
  { codigo: "0811", titulo: "Extracción de piedra ornamental y para la construcción" },
  { codigo: "0812", titulo: "Extracción de gravas y arenas, arcilla y caolín" },
  { codigo: "0891", titulo: "Extracción de minerales para productos químicos y fertilizantes" },
  { codigo: "0892", titulo: "Extracción de turba" },
  { codigo: "0893", titulo: "Extracción de sal" },
  { codigo: "0899", titulo: "Extracción de minerales no metálicos n.c.o.p." },
  { codigo: "0910", titulo: "Actividades de apoyo a la extracción de petróleo y gas natural" },
  { codigo: "0990", titulo: "Actividades de apoyo a otras industrias extractivas" },
  { codigo: "1011", titulo: "Procesado y conservación de carne" },
  { codigo: "1012", titulo: "Procesado y conservación de volatería" },
  { codigo: "1013", titulo: "Elaboración de productos cárnicos y de volatería" },
  { codigo: "1020", titulo: "Procesado y conservación de pescados, crustáceos y moluscos" },
  { codigo: "1031", titulo: "Procesado y conservación de patatas" },
  { codigo: "1032", titulo: "Elaboración de zumos de frutas y hortalizas" },
  { codigo: "1039", titulo: "Otro procesado y conservación de frutas y hortalizas" },
  { codigo: "1041", titulo: "Fabricación de aceites y grasas" },
  { codigo: "1042", titulo: "Fabricación de margarina y grasas comestibles similares" },
  { codigo: "1051", titulo: "Fabricación de productos lácteos" },
  { codigo: "1052", titulo: "Elaboración de helados" },
  { codigo: "1061", titulo: "Fabricación de productos de molinería" },
  { codigo: "1062", titulo: "Fabricación de almidones y productos amiláceos" },
  { codigo: "1071", titulo: "Fabricación de pan y de productos frescos de panadería y pastelería" },
  { codigo: "1072", titulo: "Fabricación de galletas y productos de panadería y pastelería de larga duración" },
  { codigo: "1073", titulo: "Fabricación de pastas alimenticias, cuscús y productos similares" },
  { codigo: "1081", titulo: "Fabricación de azúcar" },
  { codigo: "1082", titulo: "Fabricación de cacao, chocolate y productos de confitería" },
  { codigo: "1083", titulo: "Elaboración de café, té e infusiones" },
  { codigo: "1084", titulo: "Elaboración de especias, salsas y condimentos" },
  { codigo: "1085", titulo: "Elaboración de platos y comidas preparados" },
  { codigo: "1086", titulo: "Elaboración de preparados dietéticos, alimentos homogeneizados y alimentos para bebés" },
  { codigo: "1089", titulo: "Elaboración de otros productos alimenticios n.c.o.p." },
  { codigo: "1091", titulo: "Fabricación de productos para la alimentación de animales de granja" },
  { codigo: "1092", titulo: "Fabricación de productos para la alimentación de animales de compañía" },
  { codigo: "1101", titulo: "Destilación, rectificación y mezcla de bebidas alcohólicas" },
  { codigo: "1102", titulo: "Elaboración de vinos" },
  { codigo: "1103", titulo: "Elaboración de sidra y otras bebidas fermentadas a partir de frutas" },
  { codigo: "1104", titulo: "Elaboración de otras bebidas fermentadas no destiladas" },
  { codigo: "1105", titulo: "Fabricación de cerveza" },
  { codigo: "1106", titulo: "Fabricación de malta" },
  { codigo: "1107", titulo: "Fabricación de bebidas no alcohólicas" },
  { codigo: "1200", titulo: "Industria del tabaco" },
  { codigo: "1310", titulo: "Preparación e hilado de fibras textiles" },
  { codigo: "1320", titulo: "Fabricación de tejidos textiles" },
  { codigo: "1330", titulo: "Acabado de textiles" },
  { codigo: "1391", titulo: "Fabricación de tejidos de punto" },
  { codigo: "1392", titulo: "Fabricación de artículos confeccionados con textiles, excepto prendas de vestir" },
  { codigo: "1393", titulo: "Fabricación de alfombras y moquetas" },
  { codigo: "1394", titulo: "Fabricación de cuerdas, cordeles, bramantes y redes" },
  { codigo: "1395", titulo: "Fabricación de telas no tejidas y artículos confeccionados con ellas" },
  { codigo: "1396", titulo: "Fabricación de otros textiles técnicos e industriales" },
  { codigo: "1399", titulo: "Fabricación de otros productos textiles n.c.o.p." },
  { codigo: "1411", titulo: "Confección de prendas de vestir de cuero" },
  { codigo: "1412", titulo: "Confección de ropa de trabajo" },
  { codigo: "1413", titulo: "Confección de otras prendas de vestir exteriores" },
  { codigo: "1414", titulo: "Confección de ropa interior" },
  { codigo: "1419", titulo: "Confección de otras prendas de vestir y accesorios n.c.o.p." },
  { codigo: "1420", titulo: "Fabricación de artículos de peletería" },
  { codigo: "1431", titulo: "Confección de calcetería" },
  { codigo: "1439", titulo: "Confección de otras prendas de vestir de punto" },
  { codigo: "1511", titulo: "Preparación, curtido y acabado del cuero; preparación y teñido de pieles" },
  { codigo: "1512", titulo: "Fabricación de artículos de marroquinería, viaje y de guarnicionería y talabartería" },
  { codigo: "1520", titulo: "Fabricación de calzado" },
  { codigo: "1610", titulo: "Aserrado y cepillado de la madera" },
  { codigo: "1621", titulo: "Fabricación de chapas y tableros de madera" },
  { codigo: "1622", titulo: "Fabricación de suelos de parqué ensamblado" },
  { codigo: "1623", titulo: "Fabricación de otras estructuras de madera y piezas de carpintería y ebanistería para la construcción" },
  { codigo: "1624", titulo: "Fabricación de envases y embalajes de madera" },
  { codigo: "1629", titulo: "Fabricación de otros productos de madera; artículos de corcho, cestería y espartería" },
  { codigo: "1711", titulo: "Fabricación de pasta papelera" },
  { codigo: "1712", titulo: "Fabricación de papel y cartón" },
  { codigo: "1721", titulo: "Fabricación de papel y cartón ondulados; fabricación de envases y embalajes de papel y cartón" },
  { codigo: "1722", titulo: "Fabricación de artículos de papel y cartón para uso doméstico, sanitario e higiénico" },
  { codigo: "1723", titulo: "Fabricación de artículos de papelería" },
  { codigo: "1724", titulo: "Fabricación de papeles pintados" },
  { codigo: "1729", titulo: "Fabricación de otros artículos de papel y cartón" },
  { codigo: "1811", titulo: "Artes gráficas y servicios relacionados con las mismas" },
  { codigo: "1812", titulo: "Otras actividades de impresión y artes gráficas" },
  { codigo: "1813", titulo: "Servicios de preimpresión y preparación de soportes" },
  { codigo: "1814", titulo: "Encuadernación y servicios relacionados con la misma" },
  { codigo: "1820", titulo: "Reproducción de soportes grabados" },
  { codigo: "1910", titulo: "Coquerías" },
  { codigo: "1920", titulo: "Refino de petróleo" },
  { codigo: "2011", titulo: "Fabricación de gases industriales" },
  { codigo: "2012", titulo: "Fabricación de colorantes y pigmentos" },
  { codigo: "2013", titulo: "Fabricación de otros productos básicos de química inorgánica" },
  { codigo: "2014", titulo: "Fabricación de otros productos básicos de química orgánica" },
  { codigo: "2015", titulo: "Fabricación de fertilizantes y compuestos nitrogenados" },
  { codigo: "2016", titulo: "Fabricación de plásticos en formas primarias" },
  { codigo: "2017", titulo: "Fabricación de caucho sintético en formas primarias" },
  { codigo: "2020", titulo: "Fabricación de pesticidas y otros productos agroquímicos" },
  { codigo: "2030", titulo: "Fabricación de pinturas, barnices y revestimientos similares; tintas de imprenta y masillas" },
  { codigo: "2041", titulo: "Fabricación de jabones, detergentes y otros artículos de limpieza y abrillantamiento" },
  { codigo: "2042", titulo: "Fabricación de perfumes y cosméticos" },
  { codigo: "2051", titulo: "Fabricación de explosivos" },
  { codigo: "2052", titulo: "Fabricación de colas" },
  { codigo: "2053", titulo: "Fabricación de aceites esenciales" },
  { codigo: "2059", titulo: "Fabricación de otros productos químicos n.c.o.p." },
  { codigo: "2060", titulo: "Fabricación de fibras artificiales y sintéticas" },
  { codigo: "2110", titulo: "Fabricación de productos farmacéuticos de base" },
  { codigo: "2120", titulo: "Fabricación de especialidades farmacéuticas" },
  { codigo: "2211", titulo: "Fabricación de neumáticos y cámaras de caucho; recauchutado y renovación de neumáticos" },
  { codigo: "2219", titulo: "Fabricación de otros productos de caucho" },
  { codigo: "2221", titulo: "Fabricación de placas, hojas, tubos y perfiles de plástico" },
  { codigo: "2222", titulo: "Fabricación de envases y embalajes de plástico" },
  { codigo: "2223", titulo: "Fabricación de productos de plástico para la construcción" },
  { codigo: "2229", titulo: "Fabricación de otros productos de plástico" },
  { codigo: "2311", titulo: "Fabricación de vidrio plano" },
  { codigo: "2312", titulo: "Manipulado y transformación del vidrio plano" },
  { codigo: "2313", titulo: "Fabricación de vidrio hueco" },
  { codigo: "2314", titulo: "Fabricación de fibra de vidrio" },
  { codigo: "2319", titulo: "Fabricación y manipulado de otro vidrio, incluido el vidrio técnico" },
  { codigo: "2320", titulo: "Fabricación de productos cerámicos refractarios" },
  { codigo: "2331", titulo: "Fabricación de azulejos y baldosas de cerámica" },
  { codigo: "2332", titulo: "Fabricación de ladrillos, tejas y productos de tierras cocidas para la construcción" },
  { codigo: "2341", titulo: "Fabricación de artículos cerámicos de uso doméstico y ornamental" },
  { codigo: "2342", titulo: "Fabricación de aparatos sanitarios cerámicos" },
  { codigo: "2343", titulo: "Fabricación de aisladores y piezas aislantes de material cerámico" },
  { codigo: "2344", titulo: "Fabricación de otros productos cerámicos de uso técnico" },
  { codigo: "2349", titulo: "Fabricación de otros productos cerámicos" },
  { codigo: "2351", titulo: "Fabricación de cemento" },
  { codigo: "2352", titulo: "Fabricación de cal y yeso" },
  { codigo: "2361", titulo: "Fabricación de elementos de hormigón para la construcción" },
  { codigo: "2362", titulo: "Fabricación de elementos de yeso para la construcción" },
  { codigo: "2363", titulo: "Fabricación de hormigón fresco" },
  { codigo: "2364", titulo: "Fabricación de mortero" },
  { codigo: "2365", titulo: "Fabricación de productos de fibrocemento" },
  { codigo: "2369", titulo: "Fabricación de otros productos de hormigón, yeso y cemento" },
  { codigo: "2370", titulo: "Corte, tallado y acabado de la piedra" },
  { codigo: "2391", titulo: "Fabricación de productos abrasivos" },
  { codigo: "2399", titulo: "Fabricación de otros productos minerales no metálicos n.c.o.p." },
  { codigo: "2410", titulo: "Fabricación de productos básicos de hierro, acero y ferroaleaciones" },
  { codigo: "2420", titulo: "Fabricación de tubos, tuberías, perfiles huecos y sus accesorios, de acero" },
  { codigo: "2431", titulo: "Estirado en frío" },
  { codigo: "2432", titulo: "Laminación en frío" },
  { codigo: "2433", titulo: "Producción de perfiles en frío por conformación con plegado" },
  { codigo: "2434", titulo: "Trefilado en frío" },
  { codigo: "2441", titulo: "Producción de metales preciosos" },
  { codigo: "2442", titulo: "Producción de aluminio" },
  { codigo: "2443", titulo: "Producción de plomo, zinc y estaño" },
  { codigo: "2444", titulo: "Producción de cobre" },
  { codigo: "2445", titulo: "Producción de otros metales no férreos" },
  { codigo: "2446", titulo: "Procesado de combustibles nucleares" },
  { codigo: "2451", titulo: "Fundición de hierro" },
  { codigo: "2452", titulo: "Fundición de acero" },
  { codigo: "2453", titulo: "Fundición de metales ligeros" },
  { codigo: "2454", titulo: "Fundición de otros metales no férreos" },
  { codigo: "2511", titulo: "Fabricación de estructuras metálicas y sus componentes" },
  { codigo: "2512", titulo: "Fabricación de carpintería metálica" },
  { codigo: "2521", titulo: "Fabricación de radiadores y calderas para calefacción central" },
  { codigo: "2529", titulo: "Fabricación de otras cisternas, grandes depósitos y contenedores de metal" },
  { codigo: "2530", titulo: "Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central" },
  { codigo: "2540", titulo: "Fabricación de armas y municiones" },
  { codigo: "2550", titulo: "Forja, estampación y embutición de metales; metalurgia de polvos" },
  { codigo: "2561", titulo: "Tratamiento y revestimiento de metales" },
  { codigo: "2562", titulo: "Ingeniería mecánica por cuenta de terceros" },
  { codigo: "2571", titulo: "Fabricación de artículos de cuchillería y cubertería" },
  { codigo: "2572", titulo: "Fabricación de cerraduras y herrajes" },
  { codigo: "2573", titulo: "Fabricación de herramientas" },
  { codigo: "2591", titulo: "Fabricación de bidones y toneles de hierro o acero" },
  { codigo: "2592", titulo: "Fabricación de envases y embalajes metálicos ligeros" },
  { codigo: "2593", titulo: "Fabricación de productos de alambre, cadenas y muelles" },
  { codigo: "2594", titulo: "Fabricación de pernos y productos de tornillería" },
  { codigo: "2599", titulo: "Fabricación de otros productos metálicos n.c.o.p." },
  { codigo: "2611", titulo: "Fabricación de componentes electrónicos" },
  { codigo: "2612", titulo: "Fabricación de circuitos impresos ensamblados" },
  { codigo: "2620", titulo: "Fabricación de ordenadores y equipos periféricos" },
  { codigo: "2630", titulo: "Fabricación de equipos de telecomunicaciones" },
  { codigo: "2640", titulo: "Fabricación de productos electrónicos de consumo" },
  { codigo: "2651", titulo: "Fabricación de instrumentos y aparatos de medida, verificación y navegación" },
  { codigo: "2652", titulo: "Fabricación de relojes" },
  { codigo: "2660", titulo: "Fabricación de equipos de radiación, electromedicina y electroterapia" },
  { codigo: "2670", titulo: "Fabricación de instrumentos de óptica y equipo fotográfico" },
  { codigo: "2680", titulo: "Fabricación de soportes magnéticos y ópticos" },
  { codigo: "2711", titulo: "Fabricación de motores, generadores y transformadores eléctricos" },
  { codigo: "2712", titulo: "Fabricación de aparatos de distribución y control eléctrico" },
  { codigo: "2720", titulo: "Fabricación de pilas y acumuladores eléctricos" },
  { codigo: "2731", titulo: "Fabricación de cables de fibra óptica" },
  { codigo: "2732", titulo: "Fabricación de otros hilos y cables electrónicos y eléctricos" },
  { codigo: "2733", titulo: "Fabricación de dispositivos de cableado" },
  { codigo: "2740", titulo: "Fabricación de lámparas y aparatos eléctricos de iluminación" },
  { codigo: "2751", titulo: "Fabricación de electrodomésticos" },
  { codigo: "2752", titulo: "Fabricación de aparatos domésticos no eléctricos" },
  { codigo: "2790", titulo: "Fabricación de otro material y equipo eléctrico" },
  { codigo: "2811", titulo: "Fabricación de motores y turbinas, excepto los destinados a aeronaves, vehículos automóviles y ciclomotores" },
  { codigo: "2812", titulo: "Fabricación de equipos de transmisión hidráulica y neumática" },
  { codigo: "2813", titulo: "Fabricación de otras bombas y compresores" },
  { codigo: "2814", titulo: "Fabricación de otras llaves y válvulas" },
  { codigo: "2815", titulo: "Fabricación de cojinetes, engranajes y órganos mecánicos de transmisión" },
  { codigo: "2821", titulo: "Fabricación de hornos y quemadores" },
  { codigo: "2822", titulo: "Fabricación de maquinaria de elevación y manipulación" },
  { codigo: "2823", titulo: "Fabricación de máquinas y equipos de oficina, excepto equipos informáticos" },
  { codigo: "2824", titulo: "Fabricación de herramientas eléctricas manuales" },
  { codigo: "2825", titulo: "Fabricación de maquinaria para sistemas de ventilación y refrigeración no domésticos" },
  { codigo: "2829", titulo: "Fabricación de otra maquinaria de uso general n.c.o.p." },
  { codigo: "2830", titulo: "Fabricación de maquinaria agraria y forestal" },
  { codigo: "2841", titulo: "Fabricación de máquinas herramienta para trabajar el metal" },
  { codigo: "2849", titulo: "Fabricación de otras máquinas herramienta" },
  { codigo: "2891", titulo: "Fabricación de maquinaria para la industria metalúrgica" },
  { codigo: "2892", titulo: "Fabricación de maquinaria para las industrias extractivas y de la construcción" },
  { codigo: "2893", titulo: "Fabricación de maquinaria para la industria de la alimentación, bebidas y tabaco" },
  { codigo: "2894", titulo: "Fabricación de maquinaria para las industrias textil, de la confección y del cuero" },
  { codigo: "2895", titulo: "Fabricación de maquinaria para la industria del papel y del cartón" },
  { codigo: "2896", titulo: "Fabricación de maquinaria para la industria del plástico y el caucho" },
  { codigo: "2899", titulo: "Fabricación de otra maquinaria para usos específicos n.c.o.p." },
  { codigo: "2910", titulo: "Fabricación de vehículos de motor" },
  { codigo: "2920", titulo: "Fabricación de carrocerías para vehículos de motor; fabricación de remolques y semirremolques" },
  { codigo: "2931", titulo: "Fabricación de equipos eléctricos y electrónicos para vehículos de motor" },
  { codigo: "2932", titulo: "Fabricación de otras piezas, componentes y accesorios para vehículos de motor" },
  { codigo: "3011", titulo: "Construcción de barcos y estructuras flotantes" },
  { codigo: "3012", titulo: "Construcción de embarcaciones de recreo y deporte" },
  { codigo: "3020", titulo: "Fabricación de locomotoras y material ferroviario" },
  { codigo: "3030", titulo: "Construcción aeronáutica y espacial y su maquinaria" },
  { codigo: "3040", titulo: "Fabricación de vehículos militares de combate" },
  { codigo: "3091", titulo: "Fabricación de motocicletas" },
  { codigo: "3092", titulo: "Fabricación de bicicletas y de vehículos para personas con discapacidad" },
  { codigo: "3099", titulo: "Fabricación de otro material de transporte n.c.o.p." },
  { codigo: "3101", titulo: "Fabricación de muebles de oficina y de establecimientos comerciales" },
  { codigo: "3102", titulo: "Fabricación de muebles de cocina" },
  { codigo: "3103", titulo: "Fabricación de colchones" },
  { codigo: "3109", titulo: "Fabricación de otros muebles" },
  { codigo: "3211", titulo: "Fabricación de monedas" },
  { codigo: "3212", titulo: "Fabricación de artículos de joyería y artículos similares" },
  { codigo: "3213", titulo: "Fabricación de artículos de bisutería y artículos similares" },
  { codigo: "3220", titulo: "Fabricación de instrumentos musicales" },
  { codigo: "3230", titulo: "Fabricación de artículos de deporte" },
  { codigo: "3240", titulo: "Fabricación de juegos y juguetes" },
  { codigo: "3250", titulo: "Fabricación de instrumentos y suministros médicos y odontológicos" },
  { codigo: "3291", titulo: "Fabricación de escobas, brochas y cepillos" },
  { codigo: "3299", titulo: "Otras industrias manufactureras n.c.o.p." },
  { codigo: "3311", titulo: "Reparación de productos metálicos" },
  { codigo: "3312", titulo: "Reparación de maquinaria" },
  { codigo: "3313", titulo: "Reparación de equipos electrónicos y ópticos" },
  { codigo: "3314", titulo: "Reparación de equipos eléctricos" },
  { codigo: "3315", titulo: "Reparación de barcos" },
  { codigo: "3316", titulo: "Reparación de aeronaves y naves espaciales" },
  { codigo: "3317", titulo: "Reparación y mantenimiento de otro material de transporte" },
  { codigo: "3319", titulo: "Reparación de otros equipos" },
  { codigo: "3320", titulo: "Instalación de máquinas y equipos industriales" },
  { codigo: "3511", titulo: "Producción de energía eléctrica" },
  { codigo: "3512", titulo: "Transporte de energía eléctrica" },
  { codigo: "3513", titulo: "Distribución de energía eléctrica" },
  { codigo: "3514", titulo: "Comercio de energía eléctrica" },
  { codigo: "3515", titulo: "Producción de energía eléctrica de origen térmico convencional" },
  { codigo: "3516", titulo: "Producción de energía eléctrica de origen nuclear" },
  { codigo: "3517", titulo: "Producción de energía eléctrica de origen hidráulico" },
  { codigo: "3518", titulo: "Producción de energía eléctrica de origen eólico" },
  { codigo: "3519", titulo: "Producción de energía eléctrica de otros tipos" },
  { codigo: "3520", titulo: "Producción de gas; distribución por tubería de combustibles gaseosos" },
  { codigo: "3530", titulo: "Suministro de vapor y aire acondicionado" },
  { codigo: "3600", titulo: "Captación, depuración y distribución de agua" },
  { codigo: "3700", titulo: "Recogida y tratamiento de aguas residuales" },
  { codigo: "3811", titulo: "Recogida de residuos no peligrosos" },
  { codigo: "3812", titulo: "Recogida de residuos peligrosos" },
  { codigo: "3821", titulo: "Tratamiento y eliminación de residuos no peligrosos" },
  { codigo: "3822", titulo: "Tratamiento y eliminación de residuos peligrosos" },
  { codigo: "3831", titulo: "Separación y clasificación de materiales" },
  { codigo: "3832", titulo: "Valorización de materiales ya clasificados" },
  { codigo: "3900", titulo: "Actividades de descontaminación y otros servicios de gestión de residuos" },
  { codigo: "4110", titulo: "Promoción inmobiliaria" },
  { codigo: "4120", titulo: "Construcción de edificios residenciales y no residenciales" },
  { codigo: "4211", titulo: "Construcción de carreteras y autopistas" },
  { codigo: "4212", titulo: "Construcción de vías férreas de superficie y subterráneas" },
  { codigo: "4213", titulo: "Construcción de puentes y túneles" },
  { codigo: "4221", titulo: "Construcción de redes para fluidos" },
  { codigo: "4222", titulo: "Construcción de redes eléctricas y de telecomunicaciones" },
  { codigo: "4291", titulo: "Ingeniería hidráulica" },
  { codigo: "4299", titulo: "Construcción de otros proyectos de ingeniería civil n.c.o.p." },
  { codigo: "4311", titulo: "Demolición" },
  { codigo: "4312", titulo: "Preparación de terrenos" },
  { codigo: "4313", titulo: "Perforaciones y sondeos" },
  { codigo: "4321", titulo: "Instalaciones eléctricas" },
  { codigo: "4322", titulo: "Fontanería, instalaciones de sistemas de calefacción y aire acondicionado" },
  { codigo: "4329", titulo: "Otras instalaciones en obras de construcción" },
  { codigo: "4331", titulo: "Revocamiento" },
  { codigo: "4332", titulo: "Instalación de carpintería" },
  { codigo: "4333", titulo: "Revestimiento de suelos y paredes" },
  { codigo: "4334", titulo: "Pintura y acristalamiento" },
  { codigo: "4339", titulo: "Otro acabado de edificios" },
  { codigo: "4391", titulo: "Construcción de cubiertas" },
  { codigo: "4399", titulo: "Otras actividades de construcción especializada n.c.o.p." },
  { codigo: "4511", titulo: "Venta de automóviles y vehículos de motor ligeros" },
  { codigo: "4519", titulo: "Venta de otros vehículos de motor" },
  { codigo: "4520", titulo: "Mantenimiento y reparación de vehículos de motor" },
  { codigo: "4531", titulo: "Comercio al por mayor de repuestos y accesorios de vehículos de motor" },
  { codigo: "4532", titulo: "Comercio al por menor de repuestos y accesorios de vehículos de motor" },
  { codigo: "4540", titulo: "Venta, mantenimiento y reparación de motocicletas y de sus repuestos y accesorios" },
  { codigo: "4611", titulo: "Intermediarios del comercio de materias primas agrarias, animales vivos, materias primas textiles y productos semielaborados" },
  { codigo: "4612", titulo: "Intermediarios del comercio de combustibles, minerales, metales y productos químicos industriales" },
  { codigo: "4613", titulo: "Intermediarios del comercio de madera y materiales de construcción" },
  { codigo: "4614", titulo: "Intermediarios del comercio de maquinaria, equipo industrial, embarcaciones y aeronaves" },
  { codigo: "4615", titulo: "Intermediarios del comercio de muebles, artículos para el hogar y ferretería" },
  { codigo: "4616", titulo: "Intermediarios del comercio de textiles, prendas de vestir, peletería, calzado y artículos de cuero" },
  { codigo: "4617", titulo: "Intermediarios del comercio de productos alimenticios, bebidas y tabaco" },
  { codigo: "4618", titulo: "Intermediarios del comercio especializados en la venta de otros productos específicos" },
  { codigo: "4619", titulo: "Intermediarios del comercio de productos diversos" },
  { codigo: "4621", titulo: "Comercio al por mayor de cereales, tabaco en rama, simientes y alimentos para animales" },
  { codigo: "4622", titulo: "Comercio al por mayor de flores y plantas" },
  { codigo: "4623", titulo: "Comercio al por mayor de animales vivos" },
  { codigo: "4624", titulo: "Comercio al por mayor de cueros y pieles" },
  { codigo: "4631", titulo: "Comercio al por mayor de frutas y hortalizas" },
  { codigo: "4632", titulo: "Comercio al por mayor de carne y productos cárnicos" },
  { codigo: "4633", titulo: "Comercio al por mayor de productos lácteos, huevos, aceites y grasas comestibles" },
  { codigo: "4634", titulo: "Comercio al por mayor de bebidas" },
  { codigo: "4635", titulo: "Comercio al por mayor de productos del tabaco" },
  { codigo: "4636", titulo: "Comercio al por mayor de azúcar, chocolate y confitería" },
  { codigo: "4637", titulo: "Comercio al por mayor de café, té, cacao y especias" },
  { codigo: "4638", titulo: "Comercio al por mayor de pescados y mariscos y otros productos alimenticios" },
  { codigo: "4639", titulo: "Comercio al por mayor, no especializado, de productos alimenticios, bebidas y tabaco" },
  { codigo: "4641", titulo: "Comercio al por mayor de textiles" },
  { codigo: "4642", titulo: "Comercio al por mayor de prendas de vestir y calzado" },
  { codigo: "4643", titulo: "Comercio al por mayor de aparatos electrodomésticos" },
  { codigo: "4644", titulo: "Comercio al por mayor de porcelana, cristalería y artículos de limpieza" },
  { codigo: "4645", titulo: "Comercio al por mayor de productos perfumería y cosmética" },
  { codigo: "4646", titulo: "Comercio al por mayor de productos farmacéuticos" },
  { codigo: "4647", titulo: "Comercio al por mayor de muebles, alfombras y aparatos de iluminación" },
  { codigo: "4648", titulo: "Comercio al por mayor de artículos de relojería y joyería" },
  { codigo: "4649", titulo: "Comercio al por mayor de otros artículos de uso doméstico" },
  { codigo: "4651", titulo: "Comercio al por mayor de ordenadores, equipos periféricos y programas informáticos" },
  { codigo: "4652", titulo: "Comercio al por mayor de equipos electrónicos y de telecomunicaciones y sus componentes" },
  { codigo: "4661", titulo: "Comercio al por mayor de maquinaria, equipos y suministros agrícolas" },
  { codigo: "4662", titulo: "Comercio al por mayor de máquinas herramienta" },
  { codigo: "4663", titulo: "Comercio al por mayor de maquinaria para la minería, la construcción y la ingeniería civil" },
  { codigo: "4664", titulo: "Comercio al por mayor de maquinaria para la industria textil y de máquinas de coser y tricotar" },
  { codigo: "4665", titulo: "Comercio al por mayor de muebles de oficina" },
  { codigo: "4666", titulo: "Comercio al por mayor de otra maquinaria y equipo de oficina" },
  { codigo: "4669", titulo: "Comercio al por mayor de otra maquinaria y equipo" },
  { codigo: "4671", titulo: "Comercio al por mayor de combustibles sólidos, líquidos y gaseosos, y productos similares" },
  { codigo: "4672", titulo: "Comercio al por mayor de metales y minerales metálicos" },
  { codigo: "4673", titulo: "Comercio al por mayor de madera, materiales de construcción y aparatos sanitarios" },
  { codigo: "4674", titulo: "Comercio al por mayor de ferretería, fontanería y calefacción" },
  { codigo: "4675", titulo: "Comercio al por mayor de productos químicos" },
  { codigo: "4676", titulo: "Comercio al por mayor de otros productos semielaborados" },
  { codigo: "4677", titulo: "Comercio al por mayor de chatarra y productos de desecho" },
  { codigo: "4690", titulo: "Comercio al por mayor no especializado" },
  { codigo: "4711", titulo: "Comercio al por menor en establecimientos no especializados, con predominio en productos alimenticios, bebidas y tabaco" },
  { codigo: "4719", titulo: "Otro comercio al por menor en establecimientos no especializados" },
  { codigo: "4721", titulo: "Comercio al por menor de frutas y hortalizas en establecimientos especializados" },
  { codigo: "4722", titulo: "Comercio al por menor de carne y productos cárnicos en establecimientos especializados" },
  { codigo: "4723", titulo: "Comercio al por menor de pescados y mariscos en establecimientos especializados" },
  { codigo: "4724", titulo: "Comercio al por menor de pan y productos de panadería, confitería y pastelería en establecimientos especializados" },
  { codigo: "4725", titulo: "Comercio al por menor de bebidas en establecimientos especializados" },
  { codigo: "4726", titulo: "Comercio al por menor de productos de tabaco en establecimientos especializados" },
  { codigo: "4729", titulo: "Otro comercio al por menor de productos alimenticios en establecimientos especializados" },
  { codigo: "4730", titulo: "Comercio al por menor de combustible para la automoción en establecimientos especializados" },
  { codigo: "4741", titulo: "Comercio al por menor de ordenadores, equipos periféricos y programas informáticos en establecimientos especializados" },
  { codigo: "4742", titulo: "Comercio al por menor de equipos de telecomunicaciones en establecimientos especializados" },
  { codigo: "4743", titulo: "Comercio al por menor de equipos de audio y vídeo en establecimientos especializados" },
  { codigo: "4751", titulo: "Comercio al por menor de textiles en establecimientos especializados" },
  { codigo: "4752", titulo: "Comercio al por menor de ferretería, pintura y vidrio en establecimientos especializados" },
  { codigo: "4753", titulo: "Comercio al por menor de alfombras, moquetas y revestimientos de paredes y suelos en establecimientos especializados" },
  { codigo: "4754", titulo: "Comercio al por menor de aparatos electrodomésticos en establecimientos especializados" },
  { codigo: "4759", titulo: "Comercio al por menor de muebles, aparatos de iluminación y otros artículos para el hogar en establecimientos especializados" },
  { codigo: "4761", titulo: "Comercio al por menor de libros en establecimientos especializados" },
  { codigo: "4762", titulo: "Comercio al por menor de periódicos y artículos de papelería en establecimientos especializados" },
  { codigo: "4763", titulo: "Comercio al por menor de grabaciones de música y vídeo en establecimientos especializados" },
  { codigo: "4764", titulo: "Comercio al por menor de artículos deportivos en establecimientos especializados" },
  { codigo: "4765", titulo: "Comercio al por menor de juegos y juguetes en establecimientos especializados" },
  { codigo: "4771", titulo: "Comercio al por menor de prendas de vestir en establecimientos especializados" },
  { codigo: "4772", titulo: "Comercio al por menor de calzado y artículos de cuero en establecimientos especializados" },
  { codigo: "4773", titulo: "Comercio al por menor de productos farmacéuticos en establecimientos especializados" },
  { codigo: "4774", titulo: "Comercio al por menor de artículos médicos y ortopédicos en establecimientos especializados" },
  { codigo: "4775", titulo: "Comercio al por menor de cosméticos e higiene personal en establecimientos especializados" },
  { codigo: "4776", titulo: "Comercio al por menor de flores, plantas, semillas, fertilizantes, animales de compañía y alimentos para los mismos en establecimientos especializados" },
  { codigo: "4777", titulo: "Comercio al por menor de artículos de relojería y joyería en establecimientos especializados" },
  { codigo: "4778", titulo: "Otro comercio al por menor de artículos nuevos en establecimientos especializados" },
  { codigo: "4779", titulo: "Comercio al por menor de artículos de segunda mano en establecimientos especializados" },
  { codigo: "4781", titulo: "Comercio al por menor de productos alimenticios, bebidas y tabaco en puestos de venta y en mercados ambulantes" },
  { codigo: "4782", titulo: "Comercio al por menor de productos textiles, prendas de vestir y calzado en puestos de venta y en mercados ambulantes" },
  { codigo: "4789", titulo: "Comercio al por menor de otros productos en puestos de venta y en mercados ambulantes" },
  { codigo: "4791", titulo: "Comercio al por menor por correspondencia o Internet" },
  { codigo: "4799", titulo: "Otro comercio al por menor no realizado ni en establecimientos, ni en puestos de venta ni en mercados ambulantes" },
  { codigo: "4911", titulo: "Transporte interurbano de viajeros por ferrocarril" },
  { codigo: "4912", titulo: "Transporte de mercancías por ferrocarril" },
  { codigo: "4920", titulo: "Transporte por tubería" },
  { codigo: "4931", titulo: "Transporte terrestre urbano y suburbano de viajeros" },
  { codigo: "4932", titulo: "Transporte por taxi" },
  { codigo: "4939", titulo: "Tipos de transporte terrestre de viajeros n.c.o.p." },
  { codigo: "4941", titulo: "Transporte de mercancías por carretera" },
  { codigo: "4942", titulo: "Servicios de mudanza" },
  { codigo: "4950", titulo: "Transporte por tubería" },
  { codigo: "5010", titulo: "Transporte marítimo de pasajeros" },
  { codigo: "5020", titulo: "Transporte marítimo de mercancías" },
  { codigo: "5030", titulo: "Transporte de pasajeros por vías navegables interiores" },
  { codigo: "5040", titulo: "Transporte de mercancías por vías navegables interiores" },
  { codigo: "5110", titulo: "Transporte aéreo de pasajeros" },
  { codigo: "5121", titulo: "Transporte aéreo de mercancías" },
  { codigo: "5122", titulo: "Transporte espacial" },
  { codigo: "5210", titulo: "Depósito y almacenamiento" },
  { codigo: "5221", titulo: "Actividades anexas al transporte terrestre" },
  { codigo: "5222", titulo: "Actividades anexas al transporte marítimo y por vías navegables interiores" },
  { codigo: "5223", titulo: "Actividades anexas al transporte aéreo" },
  { codigo: "5224", titulo: "Manipulación de mercancías" },
  { codigo: "5229", titulo: "Otras actividades auxiliares al transporte" },
  { codigo: "5310", titulo: "Actividades postales sometidas a la obligación del servicio universal" },
  { codigo: "5320", titulo: "Otras actividades postales y de correos" },
  { codigo: "5510", titulo: "Hoteles y alojamientos similares" },
  { codigo: "5520", titulo: "Alojamientos turísticos y otros alojamientos de corta estancia" },
  { codigo: "5530", titulo: "Campings y aparcamientos para caravanas" },
  { codigo: "5590", titulo: "Otros alojamientos" },
  { codigo: "5610", titulo: "Restaurantes y puestos de comidas" },
  { codigo: "5621", titulo: "Provisión de comidas preparadas para eventos" },
  { codigo: "5629", titulo: "Otros servicios de comidas" },
  { codigo: "5630", titulo: "Establecimientos de bebidas" },
  { codigo: "5811", titulo: "Edición de libros" },
  { codigo: "5812", titulo: "Edición de directorios y listas de correo" },
  { codigo: "5813", titulo: "Edición de periódicos" },
  { codigo: "5814", titulo: "Edición de revistas" },
  { codigo: "5819", titulo: "Otras actividades editoriales" },
  { codigo: "5821", titulo: "Edición de videojuegos" },
  { codigo: "5829", titulo: "Edición de otros programas informáticos" },
  { codigo: "5911", titulo: "Actividades de producción cinematográfica y de vídeo" },
  { codigo: "5912", titulo: "Actividades de postproducción cinematográfica, de vídeo y de programas de televisión" },
  { codigo: "5913", titulo: "Actividades de distribución cinematográfica y de vídeo" },
  { codigo: "5914", titulo: "Actividades de exhibición cinematográfica" },
  { codigo: "5920", titulo: "Actividades de grabación de sonido y edición musical" },
  { codigo: "6010", titulo: "Actividades de radiodifusión" },
  { codigo: "6020", titulo: "Actividades de programación y emisión de televisión" },
  { codigo: "6110", titulo: "Telecomunicaciones por cable" },
  { codigo: "6120", titulo: "Telecomunicaciones inalámbricas" },
  { codigo: "6130", titulo: "Telecomunicaciones por satélite" },
  { codigo: "6190", titulo: "Otras actividades de telecomunicaciones" },
  { codigo: "6201", titulo: "Actividades de programación informática" },
  { codigo: "6202", titulo: "Actividades de consultoría informática" },
  { codigo: "6203", titulo: "Gestión de recursos informáticos" },
  { codigo: "6209", titulo: "Otros servicios relacionados con las tecnologías de la información y la informática" },
  { codigo: "6311", titulo: "Proceso de datos, hosting y actividades relacionadas" },
  { codigo: "6312", titulo: "Portales web" },
  { codigo: "6391", titulo: "Actividades de las agencias de noticias" },
  { codigo: "6399", titulo: "Otros servicios de información n.c.o.p." },
  { codigo: "6411", titulo: "Banco central" },
  { codigo: "6419", titulo: "Otra intermediación monetaria" },
  { codigo: "6420", titulo: "Actividades de las sociedades holding" },
  { codigo: "6430", titulo: "Inversión colectiva, fondos y entidades financieras similares" },
  { codigo: "6491", titulo: "Arrendamiento financiero" },
  { codigo: "6492", titulo: "Otras actividades crediticias" },
  { codigo: "6499", titulo: "Otras actividades de servicios financieros, excepto seguros y fondos de pensiones n.c.o.p." },
  { codigo: "6511", titulo: "Seguros de vida" },
  { codigo: "6512", titulo: "Seguros distintos de los seguros de vida" },
  { codigo: "6520", titulo: "Reaseguros" },
  { codigo: "6530", titulo: "Fondos de pensiones" },
  { codigo: "6611", titulo: "Administración de mercados financieros" },
  { codigo: "6612", titulo: "Actividades de intermediación en operaciones con valores y otros activos" },
  { codigo: "6619", titulo: "Otras actividades auxiliares a los servicios financieros, excepto seguros y fondos de pensiones" },
  { codigo: "6621", titulo: "Evaluación de riesgos y daños" },
  { codigo: "6622", titulo: "Actividades de agentes y corredores de seguros" },
  { codigo: "6629", titulo: "Otras actividades auxiliares a seguros y fondos de pensiones" },
  { codigo: "6630", titulo: "Actividades de gestión de fondos" },
  { codigo: "6810", titulo: "Compraventa de bienes inmobiliarios por cuenta propia" },
  { codigo: "6820", titulo: "Alquiler de bienes inmobiliarios por cuenta propia" },
  { codigo: "6831", titulo: "Agentes de la propiedad inmobiliaria" },
  { codigo: "6832", titulo: "Gestión y administración de la propiedad inmobiliaria" },
  { codigo: "6910", titulo: "Actividades jurídicas" },
  { codigo: "6920", titulo: "Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal" },
  { codigo: "7010", titulo: "Actividades de las sedes centrales" },
  { codigo: "7021", titulo: "Relaciones públicas y comunicación" },
  { codigo: "7022", titulo: "Otras actividades de consultoría de gestión empresarial" },
  { codigo: "7111", titulo: "Servicios técnicos de arquitectura" },
  { codigo: "7112", titulo: "Ingeniería y actividades relacionadas" },
  { codigo: "7120", titulo: "Ensayos y análisis técnicos" },
  { codigo: "7211", titulo: "Investigación y desarrollo experimental en biotecnología" },
  { codigo: "7219", titulo: "Otra investigación y desarrollo experimental en ciencias naturales y técnicas" },
  { codigo: "7220", titulo: "Investigación y desarrollo experimental en ciencias sociales y humanidades" },
  { codigo: "7311", titulo: "Agencias de publicidad" },
  { codigo: "7312", titulo: "Servicios de representación de medios de comunicación" },
  { codigo: "7320", titulo: "Estudios de mercado y realización de encuestas de opinión pública" },
  { codigo: "7410", titulo: "Actividades de diseño especializado" },
  { codigo: "7420", titulo: "Actividades de fotografía" },
  { codigo: "7430", titulo: "Actividades de traducción e interpretación" },
  { codigo: "7490", titulo: "Otras actividades profesionales, científicas y técnicas n.c.o.p." },
  { codigo: "7500", titulo: "Actividades veterinarias" },
  { codigo: "7711", titulo: "Alquiler de automóviles y vehículos de motor ligeros" },
  { codigo: "7712", titulo: "Alquiler de camiones" },
  { codigo: "7721", titulo: "Alquiler de artículos de deporte y recreo" },
  { codigo: "7722", titulo: "Alquiler de cintas de vídeo y discos" },
  { codigo: "7729", titulo: "Alquiler de otros efectos personales y artículos de uso doméstico" },
  { codigo: "7731", titulo: "Alquiler de maquinaria y equipo de uso agrícola" },
  { codigo: "7732", titulo: "Alquiler de maquinaria y equipo para la construcción e ingeniería civil" },
  { codigo: "7733", titulo: "Alquiler de maquinaria y equipo de oficina, incluidos ordenadores" },
  { codigo: "7734", titulo: "Alquiler de medios de navegación" },
  { codigo: "7735", titulo: "Alquiler de medios de transporte aéreo" },
  { codigo: "7739", titulo: "Alquiler de otra maquinaria, equipos y bienes tangibles n.c.o.p." },
  { codigo: "7740", titulo: "Arrendamiento de la propiedad intelectual y productos similares, excepto trabajos protegidos por los derechos de autor" },
  { codigo: "7810", titulo: "Actividades de las agencias de colocación" },
  { codigo: "7820", titulo: "Actividades de las empresas de trabajo temporal" },
  { codigo: "7830", titulo: "Otra provisión de recursos humanos" },
  { codigo: "7911", titulo: "Actividades de las agencias de viajes" },
  { codigo: "7912", titulo: "Actividades de los operadores turísticos" },
  { codigo: "7990", titulo: "Otros servicios de reservas y actividades relacionadas con los mismos" },
  { codigo: "8010", titulo: "Actividades de seguridad privada" },
  { codigo: "8020", titulo: "Servicios de sistemas de seguridad" },
  { codigo: "8030", titulo: "Actividades de investigación" },
  { codigo: "8110", titulo: "Servicios integrales a edificios e instalaciones" },
  { codigo: "8121", titulo: "Limpieza general de edificios" },
  { codigo: "8122", titulo: "Otras actividades de limpieza industrial y de edificios" },
  { codigo: "8129", titulo: "Otras actividades de limpieza" },
  { codigo: "8130", titulo: "Actividades de jardinería" },
  { codigo: "8211", titulo: "Servicios administrativos combinados" },
  { codigo: "8219", titulo: "Actividades de fotocopiado, preparación de documentos y otras actividades especializadas de oficina" },
  { codigo: "8220", titulo: "Actividades de los centros de llamadas" },
  { codigo: "8230", titulo: "Organización de convenciones y eventos comerciales" },
  { codigo: "8291", titulo: "Actividades de las agencias de cobros y de información comercial" },
  { codigo: "8292", titulo: "Actividades de envasado y empaquetado" },
  { codigo: "8299", titulo: "Otras actividades de apoyo a las empresas n.c.o.p." },
  { codigo: "8411", titulo: "Actividades generales de la Administración Pública" },
  { codigo: "8412", titulo: "Regulación de las actividades sanitarias, educativas, culturales y otros servicios sociales, excepto Seguridad Social" },
  { codigo: "8413", titulo: "Regulación de la actividad económica y contribución a su mayor eficiencia" },
  { codigo: "8421", titulo: "Asuntos exteriores" },
  { codigo: "8422", titulo: "Defensa" },
  { codigo: "8423", titulo: "Justicia" },
  { codigo: "8424", titulo: "Orden público y seguridad" },
  { codigo: "8425", titulo: "Protección civil" },
  { codigo: "8430", titulo: "Seguridad Social obligatoria" },
  { codigo: "8510", titulo: "Educación preprimaria" },
  { codigo: "8520", titulo: "Educación primaria" },
  { codigo: "8531", titulo: "Educación secundaria general" },
  { codigo: "8532", titulo: "Educación secundaria técnica y profesional" },
  { codigo: "8541", titulo: "Educación postsecundaria no terciaria" },
  { codigo: "8542", titulo: "Educación terciaria" },
  { codigo: "8551", titulo: "Educación deportiva y recreativa" },
  { codigo: "8552", titulo: "Educación cultural" },
  { codigo: "8553", titulo: "Actividades de las escuelas de conducción y pilotaje" },
  { codigo: "8559", titulo: "Otra educación n.c.o.p." },
  { codigo: "8560", titulo: "Actividades auxiliares a la educación" },
  { codigo: "8610", titulo: "Actividades hospitalarias" },
  { codigo: "8621", titulo: "Actividades de medicina general" },
  { codigo: "8622", titulo: "Actividades de medicina especializada" },
  { codigo: "8623", titulo: "Actividades odontológicas" },
  { codigo: "8690", titulo: "Otras actividades sanitarias" },
  { codigo: "8710", titulo: "Asistencia en establecimientos residenciales con cuidados sanitarios" },
  { codigo: "8720", titulo: "Asistencia en establecimientos residenciales para personas con discapacidad intelectual, enfermedad mental y drogodependencia" },
  { codigo: "8730", titulo: "Asistencia en establecimientos residenciales para personas mayores y personas con discapacidad física" },
  { codigo: "8731", titulo: "Asistencia en establecimientos residenciales para personas mayores" },
  { codigo: "8732", titulo: "Asistencia en establecimientos residenciales para personas con discapacidad física" },
  { codigo: "8790", titulo: "Otras actividades de asistencia en establecimientos residenciales" },
  { codigo: "8810", titulo: "Actividades de servicios sociales sin alojamiento para personas mayores y personas con discapacidad" },
  { codigo: "8891", titulo: "Actividades de cuidado diurno de niños" },
  { codigo: "8899", titulo: "Otros actividades de servicios sociales sin alojamiento n.c.o.p." },
  { codigo: "9001", titulo: "Artes escénicas" },
  { codigo: "9002", titulo: "Actividades auxiliares a las artes escénicas" },
  { codigo: "9003", titulo: "Creación artística y literaria" },
  { codigo: "9004", titulo: "Gestión de salas de espectáculos" },
  { codigo: "9101", titulo: "Actividades de bibliotecas y archivos" },
  { codigo: "9102", titulo: "Actividades de museos" },
  { codigo: "9103", titulo: "Gestión de lugares y edificios históricos" },
  { codigo: "9104", titulo: "Actividades de jardines botánicos, parques zoológicos y reservas naturales" },
  { codigo: "9200", titulo: "Actividades de juegos de azar y apuestas" },
  { codigo: "9311", titulo: "Gestión de instalaciones deportivas" },
  { codigo: "9312", titulo: "Actividades de los clubes deportivos" },
  { codigo: "9313", titulo: "Actividades de los gimnasios" },
  { codigo: "9319", titulo: "Otras actividades deportivas" },
  { codigo: "9321", titulo: "Actividades de los parques de atracciones y los parques temáticos" },
  { codigo: "9329", titulo: "Otras actividades recreativas y de entretenimiento" },
  { codigo: "9411", titulo: "Actividades de organizaciones empresariales y patronales" },
  { codigo: "9412", titulo: "Actividades de organizaciones profesionales" },
  { codigo: "9420", titulo: "Actividades sindicales" },
  { codigo: "9491", titulo: "Actividades de organizaciones religiosas" },
  { codigo: "9492", titulo: "Actividades de organizaciones políticas" },
  { codigo: "9499", titulo: "Otras actividades asociativas n.c.o.p." },
  { codigo: "9511", titulo: "Reparación de ordenadores y equipos periféricos" },
  { codigo: "9512", titulo: "Reparación de equipos de comunicación" },
  { codigo: "9521", titulo: "Reparación de aparatos electrónicos de audio y vídeo de uso doméstico" },
  { codigo: "9522", titulo: "Reparación de aparatos electrodomésticos y de equipos para el hogar y el jardín" },
  { codigo: "9523", titulo: "Reparación de calzado y artículos de cuero" },
  { codigo: "9524", titulo: "Reparación de muebles y artículos para el hogar" },
  { codigo: "9525", titulo: "Reparación de relojes y joyería" },
  { codigo: "9529", titulo: "Reparación de otros efectos personales y artículos de uso doméstico" },
  { codigo: "9601", titulo: "Lavado y limpieza de prendas textiles y de piel" },
  { codigo: "9602", titulo: "Peluquería y otros tratamientos de belleza" },
  { codigo: "9603", titulo: "Pompas fúnebres y actividades relacionadas" },
  { codigo: "9604", titulo: "Actividades de mantenimiento físico" },
  { codigo: "9609", titulo: "Otras servicios personales n.c.o.p." },
  { codigo: "9700", titulo: "Actividades de los hogares como empleadores de personal doméstico" },
  { codigo: "9810", titulo: "Actividades de los hogares como productores de bienes para uso propio" },
  { codigo: "9820", titulo: "Actividades de los hogares como productores de servicios para uso propio" },
  { codigo: "9900", titulo: "Actividades de organizaciones y organismos extraterritoriales" },
];

export function buscarCnaes(query: string): Cnae[] {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return CNAES.filter(
    c => c.codigo.startsWith(q) || c.titulo.toLowerCase().includes(q)
  ).slice(0, 10);
}

export function formatCnae(cnae: Cnae): string {
  return `${cnae.codigo} - ${cnae.titulo}`;
}

export function getCnaeByCode(codigo: string): Cnae | undefined {
  return CNAES.find(c => c.codigo === codigo);
}
